# Generated by Django 2.0 on 2020-07-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_management',
            name='company_logo',
            field=models.ImageField(default='media/no-img.png', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='customer_management',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer_management',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer_management',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
