# Generated by Django 2.0 on 2020-07-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_auto_20200718_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_post_management',
            name='customer_chip_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.customer_chiptiles'),
        ),
    ]
