# Generated by Django 2.0 on 2020-07-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_sentimentmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_comment_management',
            name='sentiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.sentimentMaster'),
        ),
    ]
