# Generated by Django 2.0 on 2020-07-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0006_twitter_comment_management_sentiment_uppercase'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_comment_management',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitter_comment_management',
            name='nationality_percent',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
    ]
