# Generated by Django 2.0 on 2020-07-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0007_auto_20200723_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter_comment_management',
            old_name='sentiment_uppercase',
            new_name='location',
        ),
    ]
