# Generated by Django 2.0 on 2020-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0008_auto_20200723_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter_comment_management',
            name='location_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitter_comment_management',
            name='location_lon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
