# Generated by Django 2.0 on 2020-07-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0009_auto_20200723_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_comment_management',
            name='comment_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ig_comment_management',
            name='comment_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitter_comment_management',
            name='comment_language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
