# Generated by Django 2.0 on 2020-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0010_auto_20200727_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('paramters', models.ManyToManyField(to='b2b.ReportParameter')),
            ],
        ),

    ]
