# Generated by Django 2.0 on 2020-07-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0011_reportparameter_reporttypemaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_chiptiles',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.ReportTypeMaster'),
        ),
    ]
