# Generated by Django 2.0 on 2020-07-28 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0012_customer_chiptiles_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_chiptiles',
            name='paramters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.ReportParameter'),
        ),
    ]
