# Generated by Django 2.0 on 2020-07-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0013_customer_chiptiles_paramters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_chiptiles',
            name='paramters',
        ),
        migrations.AddField(
            model_name='customer_chiptiles',
            name='paramters',
            field=models.ManyToManyField(to='b2b.ReportParameter'),
        ),
        migrations.RemoveField(
            model_name='customer_chiptiles',
            name='report_type',
        ),
        migrations.AddField(
            model_name='customer_chiptiles',
            name='report_type',
            field=models.ManyToManyField(to='b2b.ReportTypeMaster'),
        ),
    ]
