# Generated by Django 2.0 on 2020-07-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0014_auto_20200728_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_chiptiles',
            old_name='paramters',
            new_name='parameters',
        ),
        migrations.RenameField(
            model_name='reporttypemaster',
            old_name='paramters',
            new_name='parameters',
        ),
    ]
