# Generated by Django 2.0 on 2020-07-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0015_auto_20200728_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_chiptiles',
            name='parameters',
        ),
        migrations.AddField(
            model_name='customer_chiptiles',
            name='culture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_chiptiles',
            name='date_duration_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer_chiptiles',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer_chiptiles',
            name='sentiment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
