# Generated by Django 2.0 on 2020-07-29 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0016_auto_20200729_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_chiptiles',
            name='date_duration_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='customer_chiptiles',
            name='report_type',
        ),
        migrations.AddField(
            model_name='customer_chiptiles',
            name='report_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.ReportTypeMaster'),
        ),
    ]
