# Generated by Django 2.0 on 2020-08-18 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0006_delete_dummymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_django', '0010_uid_db_index'),
        ('b2b', '0017_auto_20200729_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_title', models.CharField(max_length=200, null=True)),
                ('date_duration_from', models.DateField(blank=True, null=True)),
                ('date_duration_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaAccountsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.customer_persona')),
                ('social_auth_id', models.ManyToManyField(to='social_django.UserSocialAuth')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaCultureMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.customer_persona')),
                ('social_auth_id', models.ManyToManyField(to='nationality.nationality_prediction')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaLocationsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.customer_persona')),
                ('social_auth_id', models.ManyToManyField(to='nationality.usa_cities_master')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaSentimentsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.customer_persona')),
                ('sentiment_id', models.ManyToManyField(to='b2b.sentimentMaster')),
            ],
        ),
        migrations.AlterField(
            model_name='customer_management',
            name='company_logo',
            field=models.ImageField(default='media/no-img.png', upload_to='company/'),
        ),
        migrations.AddField(
            model_name='customer_persona',
            name='customer_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2b.customer_management'),
        ),
        migrations.AddField(
            model_name='customer_persona',
            name='report_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.ReportTypeMaster'),
        ),
        migrations.AddField(
            model_name='customer_persona',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
