# Generated by Django 2.0 on 2020-08-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('nationality', '0006_delete_dummymodel'),
        ('b2b', '0019_auto_20200818_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaaccountsmaster',
            name='persona_id',
        ),
        migrations.RemoveField(
            model_name='personaaccountsmaster',
            name='social_auth_id',
        ),
        migrations.RemoveField(
            model_name='personaculturemaster',
            name='culture_id',
        ),
        migrations.RemoveField(
            model_name='personaculturemaster',
            name='persona_id',
        ),
        migrations.RemoveField(
            model_name='personalocationsmaster',
            name='loaction_id',
        ),
        migrations.RemoveField(
            model_name='personalocationsmaster',
            name='persona_id',
        ),
        migrations.RemoveField(
            model_name='personasentimentsmaster',
            name='persona_id',
        ),
        migrations.RemoveField(
            model_name='personasentimentsmaster',
            name='sentiment_id',
        ),
        migrations.AddField(
            model_name='customer_persona',
            name='culture_id',
            field=models.ManyToManyField(to='nationality.nationality_prediction'),
        ),
        migrations.AddField(
            model_name='customer_persona',
            name='loaction_id',
            field=models.ManyToManyField(to='nationality.usa_cities_master'),
        ),
        migrations.AddField(
            model_name='customer_persona',
            name='sentiment_id',
            field=models.ManyToManyField(to='b2b.sentimentMaster'),
        ),
        migrations.AddField(
            model_name='customer_persona',
            name='social_auth_id',
            field=models.ManyToManyField(to='social_django.UserSocialAuth'),
        ),
        migrations.DeleteModel(
            name='PersonaAccountsMaster',
        ),
        migrations.DeleteModel(
            name='PersonaCultureMaster',
        ),
        migrations.DeleteModel(
            name='PersonaLocationsMaster',
        ),
        migrations.DeleteModel(
            name='PersonaSentimentsMaster',
        ),
    ]
