# Generated by Django 2.0 on 2020-09-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('b2b', '0020_auto_20200818_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fb_post_management',
            name='customer_chip_ref',
        ),
        migrations.AddField(
            model_name='fb_post_management',
            name='fb_account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
            preserve_default=False,
        ),
    ]
