# Generated by Django 2.0 on 2020-09-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0021_auto_20200904_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_comment_management',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fb_comment_management',
            name='location_lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fb_comment_management',
            name='location_lon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fb_comment_management',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fb_comment_management',
            name='nationality_percent',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='fb_comment_management',
            name='resposne_sent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fb_comment_management',
            name='sentiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.sentimentMaster'),
        ),
    ]
