# Generated by Django 2.0 on 2020-09-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0022_auto_20200904_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_post_management',
            name='fb_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='b2b.fb_is_page_management'),
            preserve_default=False,
        ),
    ]
