# Generated by Django 2.0 on 2020-09-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0023_fb_post_management_fb_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_is_page_management',
            name='page_name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
