# Generated by Django 2.0 on 2020-09-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('b2b', '0024_fb_is_page_management_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='canned_response_management',
            name='social_accounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
    ]
