# Generated by Django 2.0 on 2020-09-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0027_fb_is_page_management_fb_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fb_is_page_management',
            name='page_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
