# Generated by Django 2.0 on 2020-09-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0028_fb_is_page_management_page_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='canned_response_management',
            name='fb_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='b2b.fb_is_page_management'),
        ),
    ]
