# Generated by Django 2.0 on 2020-09-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('b2b', '0029_canned_response_management_fb_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='ig_post_management',
            name='insta_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth'),
        ),
        migrations.AddField(
            model_name='ig_post_management',
            name='media_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ig_post_management',
            name='media_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
