# Generated by Django 2.0 on 2020-09-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0030_auto_20200919_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ig_post_management',
            name='customer_chip_ref',
        ),
    ]
