# Generated by Django 2.0 on 2020-09-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0031_remove_ig_post_management_customer_chip_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ig_comment_management',
            name='commented_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
