# Generated by Django 2.0 on 2020-09-21 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0033_auto_20200919_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='ig_comment_management',
            name='resposne_sent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
