# Generated by Django 2.0 on 2020-09-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0010_uid_db_index'),
        ('b2b', '0034_ig_comment_management_resposne_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='removed_fb_page_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('page_name', models.CharField(max_length=255)),
                ('user_access_token', models.CharField(max_length=255)),
                ('app_access_token', models.CharField(max_length=255)),
                ('page_access_token', models.CharField(max_length=255)),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_django.UserSocialAuth')),
            ],
        ),
    ]
