# Generated by Django 2.0 on 2020-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0036_fb_is_page_management_ig_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ig_post_management',
            name='media_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ig_post_management',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
