# Generated by Django 2.0 on 2020-07-03 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0002_nationality_prediction_tweet_user_data_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='tweet_analytics_processed_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_user_id', models.BigIntegerField(blank=True, null=True)),
                ('tweet_username', models.CharField(blank=True, max_length=255, null=True)),
                ('tweet_user_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tweet_user_description', models.TextField(blank=True, null=True)),
                ('tweet_user_profile_created_at', models.DateTimeField(blank=True, null=True)),
                ('tweet_user_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tweet_user_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tweet_user_nationality_predicted', models.BooleanField(default=False)),
                ('tweet_user_jurisdiction', models.CharField(blank=True, max_length=255, null=True)),
                ('tweet_user_percent', models.DecimalField(decimal_places=10, default=0.0, max_digits=19)),
                ('tweet_id', models.BigIntegerField()),
                ('tweet_text', models.TextField(blank=True, null=True)),
                ('tweet_lang', models.CharField(blank=True, max_length=15, null=True)),
                ('tweet_created_datetime', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('city_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationality.usa_cities_master')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationality.hashtag_collections')),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nationality.usa_states_master')),
            ],
            options={
                'verbose_name_plural': 'Tweet Preprocess Data',
                'verbose_name': 'Tweet Preprocess Data',
            },
        ),
        migrations.AddField(
            model_name='forebears_logging',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forebears_logging',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nationality_prediction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nationality_prediction',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
