# Generated by Django 2.0 on 2020-07-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0003_auto_20200703_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='chiptiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_title', models.CharField(max_length=200, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('nationalities', models.TextField(null=True)),
                ('locations', models.TextField(null=True)),
                ('hashtags', models.TextField(null=True)),
            ],
        ),
    ]
