# Generated by Django 2.0 on 2020-07-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0005_dummymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
