# Generated by Django 2.0 on 2020-10-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nationality', '0006_delete_dummymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_analytics_processed_data',
            name='tweet_sentiment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
