# Generated by Django 2.0 on 2020-10-30 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeListeningFIlter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.CharField(blank=True, max_length=255, null=True)),
                ('cities', models.CharField(blank=True, max_length=255, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
                ('cultures', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
